export type ServiceStatus = "UP" | "DOWN" | "ERROR" | "BUILDING";
export type RuntimeStatus = "running" | "stopped" | "restarting";
export type ServicesLanguage = "node" | "python";

export type ResourcesReg = {
    cpuPercent?: number;
    memoryMb?: number;
}

export type ServiceResource = {
    limit?: ResourcesReg;
    usage?: ResourcesReg & { memoryPercent?: number; }
}

export type ServicePort = {
    internal: number;
    external: number;
} 

export type ServiceEndpoint = {
    host: string;
    port: number;
    protocol: "http" | "https"
    basePath: string;
    url: string;
    autoGenerated: boolean;
}

export type BuildMetadata = {
    imageName : string;
    lastBuildAt?:string;
}

export type ServiceContainerRef = {
    status: RuntimeStatus;
    containerId: string;
    containerName: string;
    image: {
        id : string,
        name? : string,
    };
}

// ====================================================

export type ServiceMetadata = {
    id: string;
    displayName: string;
    description: string;
    language: ServicesLanguage;
    status: ServiceStatus;
    runtimeStatus: RuntimeStatus;
    createdAt: string;
    updatedAt: string;
}

export type ServiceRecord = {
    metadata: ServiceMetadata;
    container: ServiceContainerRef;
    ports: ServicePort;
    endpoint: ServiceEndpoint;
    resources: ServiceResource;
    build: BuildMetadata;
}

// ====================================================

export type ContainerMetricUsage = {
  containerId: string;
  containerName: string;
  cpu: number;
  ram: number;
  ts: number;
  status: RuntimeStatus;
}

export type ContainersMetricsResponse = {
  scope: "single" | "many" | "all";
  items: ContainerMetricUsage[];
  summary: {
    cpuAvg: number;
    ramAvg: number;
    containers: number;
  };
}
