import { ServiceRecord, ServicesLanguage } from "@shared/domain.types";
export const HOST = process.env.HOST ?? "localhost";

export type newRecordProps = {
    id              : string,
    name            : string,
    language        : ServicesLanguage,
    now             : string,
    containerName   : string,
    imageName       : string,
    port            : number,
    description?    : string,
}

export function newRecord ({ id, name, language, now, containerName, imageName, port ,description="" } : newRecordProps ) : ServiceRecord {
    return {
            metadata: {
                id,
                displayName  : name,
                description,
                language,
                status       : "BUILDING",
                runtimeStatus: "stopped",
                createdAt    : now,
                updatedAt    : now,
            },
            container: {
                status       : "stopped",
                containerName,
                image        : { id: "", name: imageName },
            },
            ports: {
                internal: port,
                external: port,
            },
            endpoint: {
                host         : HOST,
                port,
                protocol     : "http",
                basePath     : `/${id}`,
                url          : `http://${HOST}:${port}/${id}`,
                autoGenerated: true,
            },
            resources: {},
            build: {
                imageName,
                lastBuildAt: now,
            },
        };
    
}