import { ServiceRecord, ServicesLanguage } from "@shared/domain.types";
export const HOST = process.env.HOST ?? "localhost";

export const DEFAULT_PORT_START = 4010;
export const DEFAULT_PORT_END = 4999;

export type newRecordProps = {
    id: string,
    name: string,
    language: ServicesLanguage,
    now: string,
    containerName: string,
    imageName: string,
    internalPort: number,
    externalPort: number,
    description?: string,
}

export function newRecord({ id, name, language, now, containerName, imageName, internalPort, externalPort, description = "" }: newRecordProps): ServiceRecord {
    return {
        metadata: {
            id,
            displayName: name,
            description,
            language,
            status: "BUILDING",
            runtimeStatus: "stopped",
            createdAt: now,
            updatedAt: now,
        },
        container: {
            containerId: "",
            status: "stopped",
            containerName,
            image: { id: "", name: imageName },
        },
        ports: {
            internal: internalPort,
            external: externalPort,
        },
        endpoint: {
            host: HOST,
            port: externalPort,
            protocol: "http",
            basePath: `/${id}`,
            url: `http://${HOST}:${externalPort}/${id}`,
            autoGenerated: true,
        },
        resources: {},
        build: {
            imageName,
            lastBuildAt: now,
        },
    };
}