import * as crypto from "crypto";
import * as registry from "@libs/registry/registry.service";
import * as dockerService from "@libs/docker/docker.service";
import { HTTPError } from "@modules/app/error.model";
import type { CreateServiceBody } from "./microservices.schema";
import type { ServiceRecord } from "@shared/domain.types";
import { SOURCE_FILENAME } from "@libs/docker/docker.service";
import * as path from "path";
import * as fs from "fs/promises";

const HOST = process.env.HOST ?? "localhost";

export async function createMicroservice(body: CreateServiceBody): Promise<ServiceRecord> {
    const { name, description, language, sourceCode, port } = body;

    // Ver si no existe en el registro
    const existing = await registry.readRegistry();
    const nameExists = existing.services.some((s) => s.metadata.id === name);
    if (nameExists)
        throw new HTTPError({ statusCode: 409, type: "CONFLICT", message: `Ya existe un microservicio con el nombre '${name}'` });

    const id        = name;
    const imageName = `ms-${id}:latest`;
    const containerName = `ms-${id}`;
    const now       = new Date().toISOString();

    // Armar el ServiceRecord inicial con status BUILDING
    const record: ServiceRecord = {
        metadata: {
            id,
            displayName  : name,
            description: "",
            language,
            status       : "BUILDING",
            runtimeStatus: "stopped",
            createdAt    : now,
            updatedAt    : now,
        },
        container: {
            status       : "stopped",
            containerName,
            image        : { id: "", name: imageName },
        },
        ports: {
            internal: port,
            external: port,
        },
        endpoint: {
            host         : HOST,
            port,
            protocol     : "http",
            basePath     : `/${id}`,
            url          : `http://${HOST}:${port}/${id}`,
            autoGenerated: true,
        },
        resources: {},
        build: {
            imageName,
            lastBuildAt: now,
        },
    };

    // Queda en el registro antes del build
    await registry.appendService(record);

    // Crear carpeta del microservicio, se guarda codigo y metadata (confirmar)
    const serviceDir = path.join(process.cwd(), "microservices", id);
    await fs.mkdir(serviceDir, { recursive: true });

    await fs.writeFile(path.join(serviceDir, SOURCE_FILENAME[language]), sourceCode, "utf-8");

    await fs.writeFile(
        path.join(serviceDir, "service.json"),
        JSON.stringify({ id, language, port, createdAt: now }, null, 2),
        "utf-8"
    );

    try {
        await dockerService.buildImageFromSource({ serviceId: id, language, sourceCode, port, imageName });

        // Levanta contenedor
        const containerId = await dockerService.startContainer({
            imageName,
            containerName,
            internalPort: port,
            externalPort: port,
        });

        // Se actualiza el registro con el estado final
        const updated: Partial<ServiceRecord> = {
            metadata : { ...record.metadata, status: "UP", runtimeStatus: "running", updatedAt: new Date().toISOString() },
            container: { status: "running", containerId, containerName, image: { id: containerId, name: imageName } },
        };
        await registry.updateService(id, updated);

        return { ...record, ...updated };

    } catch (err: any) {
        await registry.updateService(id, {
            metadata: { ...record.metadata, status: "ERROR", updatedAt: new Date().toISOString() },
        });

        throw new HTTPError({
            statusCode : 500,
            type       : "INTERNAL_ERROR",
            message    : "Error al construir o levantar el microservicio",
            details    : err?.message ?? String(err),
        });
    }
}

export async function listMicroservices() {
    const services = await registry.getAllServices();

    // Llamada a Docker para la lista de contenedores
    const containers = await dockerService.getContainerList();

    return services.map((service) => {
        const match = containers.find(
            (c) => c.containerName === service.container.containerName
        );

        const runtimeStatus = match?.status ?? "stopped"; // Caso donde no esté en la lista de contenedores
        const status = runtimeStatus === "running" ? "UP"
                     : !match                      ? "ERROR"
                     : "DOWN";

        return {
            ...service,
            metadata: { ...service.metadata, runtimeStatus, status },
        };
    });
}

export async function getMicroserviceById(id: string) {
    const service = await registry.findServiceById(id);
    if (!service)
        throw new HTTPError({ statusCode: 404, type: "NOT_FOUND", message: `No existe un microservicio con id '${id}'` });

    const containers = await dockerService.getContainerList();
    const match = containers.find((c) => c.containerName === service.container.containerName);

    const runtimeStatus = match?.status ?? "stopped";
    const status = runtimeStatus === "running" ? "UP"
                 : !match                      ? "ERROR"
                 : "DOWN";

    return {
        ...service,
        metadata: { ...service.metadata, runtimeStatus, status },
    };
}

export async function deleteMicroservice(id: string): Promise<void> {
    const service = await registry.findServiceById(id);
    if (!service)
        throw new HTTPError({ statusCode: 404, type: "NOT_FOUND", message: `No existe el microservicio con id '${id}'` });

    await dockerService.stopAndRemoveContainer(service.container.containerName);
    await dockerService.removeImage(service.build.imageName);

    // Elimina la carpeta del microservicio (confirmar)
    const serviceDir = path.join(process.cwd(), "microservices", id);
    await fs.rm(serviceDir, { recursive: true, force: true });

    // Elimina del registry
    await registry.removeService(id);
}
// Manejo de estado de los microservicios
export async function startMicroservice(id: string) {
    const service = await registry.findServiceById(id);
    if (!service)
        throw new HTTPError({ statusCode: 404, type: "NOT_FOUND", message: `No existe un microservicio con id '${id}'` });

    await dockerService.startExistingContainer(service.container.containerName);

    await registry.updateService(id, {
        metadata: { ...service.metadata, status: "UP", runtimeStatus: "running", updatedAt: new Date().toISOString() },
    });

    return { id, status: "UP", runtimeStatus: "running" };
}

export async function stopMicroservice(id: string) {
    const service = await registry.findServiceById(id);
    if (!service)
        throw new HTTPError({ statusCode: 404, type: "NOT_FOUND", message: `No existe un microservicio con id '${id}'` });

    await dockerService.stopExistingContainer(service.container.containerName);

    await registry.updateService(id, {
        metadata: { ...service.metadata, status: "DOWN", runtimeStatus: "stopped", updatedAt: new Date().toISOString() },
    });

    return { id, status: "DOWN", runtimeStatus: "stopped" };
}

export async function restartMicroservice(id: string) {
    const service = await registry.findServiceById(id);
    if (!service)
        throw new HTTPError({ statusCode: 404, type: "NOT_FOUND", message: `No existe un microservicio con id '${id}'` });

    await dockerService.restartExistingContainer(service.container.containerName);

    await registry.updateService(id, {
        metadata: { ...service.metadata, status: "UP", runtimeStatus: "running", updatedAt: new Date().toISOString() },
    });

    return { id, status: "UP", runtimeStatus: "running" };
}